# Generated by Django 2.0.7 on 2018-07-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(to='menu.Item'),
        ),
    ]
